### PR TITLE
Add ability to redact params and headers

### PR DESCRIPTION
**Pull request by nberger**
Partial implementation of #13 (what's missing: include defaults or documentation for known auth libraries like friend, buddy, etc)

### CODE REVIEW

**Comment by kernelp4nic** [comment]
Working great with friend simple auth

`2015-10-19 13:38:32,186 INFO  ring.logger.tools-logging:   \ - - - -  Params: {:password "[REDACTED]", :username "admin"}`

Make sense that cookies needs to be redacted by default?

``` clojure
(logger/wrap-with-logger {:redact-fn (msg/redact-some #{"cookie"} (constantly "[I WAS REDACTED]"))})
```

`"cookie" "[I WAS REDACTED]"`

**Comment by nberger** [comment]
@kernelp4nic: Thanks for the testing :)

I'll take a look into friend. I guess `cookie` is specific to the http basic auth workflow friend, I'm not sure yet but I think I'll leave library-specific keys separate from the default, but easy to use via something like `(logger/wrap-with-logger {:redact-keys msg/friend-redact-keys})`. I'll let you know what I come up with (suggestions welcome though).

**Comment by nberger** [comment]
@kernelp4nic: I'm merging this PR as is, without explicit support for friend or any other library. I'll take a little more time to play a bit with friend and buddy before adding support for them.

Of course PRs adding that support are more than welcome. In that case, I'd love to get links to the relevant library documentation and/or a specific example added in the example app (it's here, in the `example` directory).

Again, thanks for trying the changes here!

**Pull request merged**
